version: "3"
services:

    dbispconfig:
        container_name: dbispconfig
        image: mysql:latest
        restart: always
        stdin_open: true
        tty: true
        environment:
            - MYSQL_ROOT_PASSWORD=dbispconfigpass
            - MYSQL_ROOT_HOST='%'
        volumes:
         - dbispconfig:/var/lib/mysql
        ports:
          - 3306:3306
        networks:
          internal:
            ipv4_address: 10.0.2.4


    ispconfig3:
        container_name: ispconfig3
        build: .
        image: ispconfig3-php8.2:debian12.6-slim
        restart: always
        stdin_open: true
        tty: true
#        privileged: true
        environment:
            - LANGUAGE=C
            - LANG=C.UTF-8
            - LC_ALL=C.UTF-8
            - HOSTNAME=myhost.test.com
        volumes:
          - ./debian.cnf:/etc/mysql/debian.cnf
          - ./supervisor:/etc/supervisor
          - ./usr/local/ispconfig:/usr/local/ispconfig
#          - ./data/letsencrypt:/etc/letsencrypt
#          - ./data/etc/apache2/sites-available:/etc/apache2/sites-available
#          - ./data/etc/apache2/sites-enabled:/etc/apache2/sites-enabled
#          - ./data/www:/var/www/
#          - ./data/backup:/var/backup/
#          - ./data/usr/ispconfig:/usr/local/ispconfig
#          - ./data/etc/cron.d:/etc/cron.d
        hostname: myhost.test.com
        extra_hosts:
          - "myhost.test.com:10.0.1.3"
        cap_add:
          - SYS_ADMIN
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
            - "8081:8081"
        networks:
           external:
              ipv4_address: 10.0.1.3
           internal:
              ipv4_address: 10.0.2.3
        entrypoint: /bin/sh -c "/usr/bin/supervisord"

volume:
  dbispconfig

networks:
    external:
        external:
            name: external
    internal:
        external:
            name: internal
